swagger: '2.0'
info:
    title: Bank Argent API documentation
    description: Contains all available API endpoints in this codebase
    version: '1.0.0'
    termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
    - http
paths:
    /user/login:
        post:
            tags:
                - User Module
            summary: Login
            description: API for Login
            parameters:
                - in: body
                  name: body
                  description: Login Payload
                  required: true
                  schema:
                      $ref: '#/definitions/Login'
            produces:
                - application/json
            responses:
                '200':
                    description: Login Successfully
                    schema:
                        $ref: '#/definitions/LoginResponse'
                '400':
                    description: Invalid Fields
                '500':
                    description: Internal Server Error

    /user/signup:
        post:
            tags:
                - User Module
            summary: Signup
            description: API for Signup
            parameters:
                - in: body
                  name: body
                  description: Signup Payload
                  required: true
                  schema:
                      $ref: '#/definitions/User'
            produces:
                - application/json
            responses:
                '200':
                    description: Signup Successfully
                    schema:
                        $ref: '#/definitions/ApiResponse'
                '400':
                    description: Invalid Fields
                '500':
                    description: Internal Server Error

    /user/profile:
        post:
            security:
                - Bearer: []
            tags:
                - User Module
            summary: User Profile API
            description: API for fetching a user profile
            parameters:
                - in: header
                  name: Authorization
                  type: string
                  description: Attach Bearer JWT token
                  required: true
            produces:
                - application/json
            responses:
                '200':
                    description: User profile retrieved successfully
                    schema:
                        $ref: '#/definitions/ApiResponse'
                '400':
                    description: Invalid Fields
                '500':
                    description: Internal Server Error

        put:
            security:
                - Bearer: []
            tags:
                - User Module
            summary: User Profile API
            description: API for updating a user profile
            parameters:
                - in: header
                  name: Authorization
                  type: string
                  description: Attach Bearer JWT token
                  required: true
                - in: body
                  name: body
                  description: Update user profile attributes
                  required: true
                  schema:
                      $ref: '#/definitions/UserProfile'
            produces:
                - application/json
            responses:
                '200':
                    description: User profile updated successfully
                    schema:
                        $ref: '#/definitions/ApiResponse'
                '400':
                    description: Invalid Fields
                '500':
                    description: Internal Server Error

    /transactions/:
        get:
            tags:
                - Module des Transactions
            summary: Récupérer toutes les transactions pour le mois en cours
            parameters:
                - in: header
                  name: Authorization
                  type: string
                  description: Attach Bearer JWT token
                  required: true
            produces:
                - application/json
            responses:
                '200':
                    description: Transactions récupérées avec succès
                '400':
                    description: Paramètres invalides
                '500':
                    description: Erreur interne du serveur

    /transactions/{transactionId}:
        get:
            tags:
                - Module des Transactions
            summary: Détails d'une transaction
            parameters:
                - in: header
                  name: Authorization
                  type: string
                  description: Attach Bearer JWT token
                  required: true
                - in: path
                  name: transactionId
                  type: integer
                  required: true
                  description: ID de la transaction
            produces:
                - application/json
            responses:
                '200':
                    description: Détails de la transaction récupérés avec succès
                '404':
                    description: Transaction non trouvée
                '500':
                    description: Erreur interne du serveur

        put:
            tags:
                - Module des Transactions
            summary: Modifier les détails d'une transaction
            parameters:
                - in: header
                  name: Authorization
                  type: string
                  description: Attach Bearer JWT token
                  required: true
                - in: path
                  name: transactionId
                  type: integer
                  required: true
                  description: ID de la transaction à modifier
                - in: body
                  name: transaction
                  description: Informations modifiées de la transaction
                  required: true
                  schema:
                      $ref: '#/definitions/Transaction'
            responses:
                '200':
                    description: Transaction modifiée avec succès
                '400':
                    description: Paramètres invalides
                '404':
                    description: Transaction non trouvée
                '500':
                    description: Erreur interne du serveur

securityDefinitions:
    Bearer:
        type: apiKey
        name: Authorization
        in: header

definitions:
    User:
        properties:
            email:
                type: string
                description: user email
            password:
                type: string
                description: user password
            firstName:
                type: string
                description: user first name
            lastName:
                type: string
                description: user last name

    Login:
        properties:
            email:
                type: string
                description: user email
            password:
                type: string
                description: user password

    UserProfile:
        properties:
            email:
                type: string
                description: user email
            firstName:
                type: string
                description: user first name
            lastName:
                type: string
                description: user last name

    LoginResponse:
        properties:
            token:
                type: string
                description: JWT token

    Transaction:
        properties:
            category:
                type: string
                description: Catégorie de la transaction
            note:
                type: string
                description: Note pour la transaction

    ApiResponse:
        properties:
            code:
                type: integer
                format: int32
            message:
                type: string
